name: CD

on:
  push:
    branches:
      - [main, master]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucagregolini/argocd-fullcycle
          tags: ${{ github.sha }}, latest
