apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: go-argos-app

images:
- name: go-argos-app
  newName: lucagregolini/argocd-fullcycle
  newTag: d344a610c076ac59e156f12c26a90ace6d0c5584
