apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: go-argos-app

images:
- name: go-argos-app
  newName: lucagregolini/argocd-fullcycle
  newTag: f8735f3e57642d44ce04623de74ea7c19e4b2971
